### ISSUE TITLE
Milestone 1 Issues

### ISSUE THREAD

**Issue by aimirza** [UBC-MDS/DSCI_522_greenhouse_emissions_comparisons#66]
**You may close this issue when all issues are resolved and checked.** 

**Mechanics**
- [x] Good practice to have your documents in a doc folder, not in your results folder. 
- [x] Name 1_load_data.R doesn't match its function. 

**Reasoning**
- [x] Provide context to your question; what is the relevance of your question? 
- [x] As discussed, because of your question it would be more appropriate to compare the sum of gas emissions between those years for each country, not the mean emission per year. 

**Visualization**
- [x] More descriptive Figure and table captions. Captions should stand alone. Meaning, the reader should understand the figure by examining the graph and caption alone, and not refer back to the text. For example: "Figure 1. Mean pregnancy length for first babies pregnancy and for other (non-first baby) pregnancy length. Error bars represent 95% confidence intervals generated by boostrapping.)"
- [x] You have (kt) in some of your y-axes. What does it mean? 
- [x] What do the letters mean in figure 2? 

**Quality -- Readability and Documentation**
- [x] In the script 2_data_exploration.R what is the purpose of having the code   `sum(is.na(clean_data_GH$Value))` if it is not used? You can make a function that if there are missing values it will remove it. Same issue with `sum(clean_data_GH$Value == 0)`

**Quality -- Robustness and Maintainability**
Great. 

**Grammar and Spelling**
_README.md_
> The analysis aims to find if these is a differences of greenhouse gas emissions..,
- [x] Should be:  if there* are* differences... 
- [x] Misspeled emission

_Report_
Misspelled: research

**Comment by mkeyim** [comment]
@K3ra-y should `1_load_data.R` be changed to `1_read_data.R` ?

**Comment by aimirza** [comment]
That script does more than load or reads data, it "cleans" it and prepares is for the next script.

**Comment by chaomander2018** [comment]
Hi @aimirza. letters in Figure 2 are explained in our figure captions in the report. 
> Different letters indicate significant differences between the groups (pairwise comparison, p < 0.05).
Thank you!

**Comment by K3ra-y** [comment]
Hi @aimirza `sum(is.na(clean_data_GH$Value))` is the part of explanatory data analysis as referred  on `README.md` to [this paper](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/j.2041-210X.2009.00001.x). Since we have not seen any missing values we did not remove any.

**Comment by aimirza** [comment]
> @aimirza I thought we agreed on how the analysis were performed. Can you clarify your comment below?
> "As discussed, because of your question it would be more appropriate to compare the sum of gas emissions between those years for each country, not the mean emission per year."
> Thank you!

I thought you said you wanted to tweak the question so that you wouldn't have to change the analysis (i.e. sum of gas emissions vs mean of all the years)

**Comment by K3ra-y** [comment]
Thank you for the feedback @aimirza
