### ISSUE TITLE
Milestone 2 Issues

### ISSUE THREAD

**Issue by aimirza** [UBC-MDS/DSCI_522_greenhouse_emissions_comparisons#73]
Makefile looks good. 

- [x] Explain how to run the Makefile (e.g., go to root, run these codes, etc) and describe their Makefile (including inputs and outputs) all in the main  README.md file? Similar to [this group](https://github.com/UBC-MDS/DSCI_522_jchen9314_apchiodo)

- [x] Please make the figures larger. 

- [x] letters in Fig 2 are still unclear. Look at how other articles show the significance between multiple groups. 

You dont need a script just to upload data.

**Comment by mkeyim** [comment]
Addressed all issues!

**Comment by K3ra-y** [comment]
1.  7f8b73d06fc421dba558123e8fca15fd1ce1bcd4
2.  ff4576e4a5b175ce239f0fecfb58cca27f46da92
3.  a945d154fabc8a749698b96634d3eb27bcbbf757 and ff4576e4a5b175ce239f0fecfb58cca27f46da92
